export default [
    'PAYMENT_INITIATED',
    'PAYMENT_INITIATED_WITH_PENALTY',
    'APPLICATION_REVIEW',
    'MANUAL_PROCESSING',
    'PRE_PROCEEDING_CONDITIONS',
    'ADDITIONAL_DOCUMENTS_REQUESTED',
    'FEE_CERTIFICATION',
    'SHORTFALL',
    'SHORTFALL_REVIEW',
    'NOTIFICATION',
    'APPLICATION_CLOSURE',
    'POST_PROCESSING_APPLICATION_REVIEW',
    'POST_PROCESSING_FINAL_REVIEW',
    'ADMIN_REVIEW',
    'SINGLE_WINDOW',
    'DECISION'
]