export default {
  layout_type: null,
  layout_category: null,
  plot_area: null,
  proposed_site_area_for_approval: null,
  construction_type: null,
  land_type: null,
  survey_no: null,
  ulb_name: null,
  mandal: null,
  village: null,
  revenue_village: null,
  if_site_area_more_than_proposed_reason: null,
  is_site_under_sanctioned_master_plan: null,
  land_use_as_per_master_plan: null,
  land_allotment_by_govt: null,
  market_value: null,
  address: null,

  airport_vicinity: null,
  national_monument_vicinity: null,
  heritage_structure_vicinity: null,
  oil_gas_pipeline_vicinity: null,
  religious_structure_vicinity: null,

  is_approach_road_existing: null,
  road_width: null,
  approach_road_connect_with_public_road: null,
  status_of_road: null,
  commencement_of_work_onsite: null,

  boundary_schedule_north: null,
  boundary_schedule_east: null,
  boundary_schedule_west: null,
  boundary_schedule_south: null,
};